// <auto-generated />
using System;
using FootballAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FootballAPI.Migrations
{
    [DbContext(typeof(FootballDbContext))]
    [Migration("20250820100117_UpdateDatabase")]
    partial class UpdateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FootballAPI.Models.FriendRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ResponsedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId", "ReceiverId")
                        .IsUnique();

                    b.ToTable("FriendRequests");
                });

            modelBuilder.Entity("FootballAPI.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.Property<int?>("TeamId1")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MatchDate");

                    b.HasIndex("TeamId");

                    b.HasIndex("TeamId1");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("FootballAPI.Models.MatchTeams", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Goals")
                        .HasColumnType("int");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("MatchId", "TeamId")
                        .IsUnique();

                    b.ToTable("MatchTeams");
                });

            modelBuilder.Entity("FootballAPI.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Errors")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProfileImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.Property<int>("Stamina")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("FirstName", "LastName");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Errors = 2,
                            FirstName = "Ion",
                            IsAvailable = true,
                            IsEnabled = true,
                            LastName = "Popescu",
                            Rating = 8.5,
                            Speed = 2,
                            Stamina = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Errors = 2,
                            FirstName = "Marius",
                            IsAvailable = true,
                            IsEnabled = true,
                            LastName = "Ionescu",
                            Rating = 7.8000001907348633,
                            Speed = 2,
                            Stamina = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Errors = 2,
                            FirstName = "Alex",
                            IsAvailable = true,
                            IsEnabled = true,
                            LastName = "Georgescu",
                            Rating = 7.1999998092651367,
                            Speed = 2,
                            Stamina = 2,
                            UserId = 5
                        },
                        new
                        {
                            Id = 4,
                            Errors = 2,
                            FirstName = "Razvan",
                            IsAvailable = true,
                            IsEnabled = true,
                            LastName = "Moldovan",
                            Rating = 8.1000003814697266,
                            Speed = 2,
                            Stamina = 2,
                            UserId = 6
                        },
                        new
                        {
                            Id = 5,
                            Errors = 2,
                            FirstName = "Cristian",
                            IsAvailable = true,
                            IsEnabled = true,
                            LastName = "Stancu",
                            Rating = 6.9000000953674316,
                            Speed = 2,
                            Stamina = 2,
                            UserId = 7
                        },
                        new
                        {
                            Id = 6,
                            Errors = 2,
                            FirstName = "Andrei",
                            IsAvailable = true,
                            IsEnabled = true,
                            LastName = "Vasilescu",
                            Rating = 7.6999998092651367,
                            Speed = 2,
                            Stamina = 2,
                            UserId = 8
                        },
                        new
                        {
                            Id = 7,
                            Errors = 2,
                            FirstName = "Florin",
                            IsAvailable = true,
                            IsEnabled = true,
                            LastName = "Dumitru",
                            Rating = 8.3000001907348633,
                            Speed = 2,
                            Stamina = 2,
                            UserId = 9
                        },
                        new
                        {
                            Id = 8,
                            Errors = 2,
                            FirstName = "Gabriel",
                            IsAvailable = true,
                            IsEnabled = true,
                            LastName = "Ciobanu",
                            Rating = 7.4000000953674316,
                            Speed = 2,
                            Stamina = 2,
                            UserId = 10
                        },
                        new
                        {
                            Id = 9,
                            Errors = 2,
                            FirstName = "Lucian",
                            IsAvailable = true,
                            IsEnabled = true,
                            LastName = "Matei",
                            Rating = 6.8000001907348633,
                            Speed = 2,
                            Stamina = 2,
                            UserId = 11
                        },
                        new
                        {
                            Id = 10,
                            Errors = 2,
                            FirstName = "Daniel",
                            IsAvailable = true,
                            IsEnabled = true,
                            LastName = "Radu",
                            Rating = 7.9000000953674316,
                            Speed = 2,
                            Stamina = 2,
                            UserId = 12
                        },
                        new
                        {
                            Id = 11,
                            Errors = 2,
                            FirstName = "Mihai",
                            IsAvailable = true,
                            IsEnabled = true,
                            LastName = "Popa",
                            Rating = 8.0,
                            Speed = 2,
                            Stamina = 2,
                            UserId = 13
                        },
                        new
                        {
                            Id = 12,
                            Errors = 2,
                            FirstName = "Stefan",
                            IsAvailable = true,
                            IsEnabled = true,
                            LastName = "Nicolae",
                            Rating = 7.5999999046325684,
                            Speed = 2,
                            Stamina = 2,
                            UserId = 14
                        });
                });

            modelBuilder.Entity("FootballAPI.Models.PlayerMatchHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<int?>("MatchTeamsId")
                        .HasColumnType("int");

                    b.Property<double>("PerformanceRating")
                        .HasColumnType("float");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("MatchTeamsId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable("PlayerMatchHistory");
                });

            modelBuilder.Entity("FootballAPI.Models.PlayerOrganiser", b =>
                {
                    b.Property<int>("OrganiserId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("OrganiserId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerOrganisers");
                });

            modelBuilder.Entity("FootballAPI.Models.ResetPasswordToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_PasswordResetTokens_ExpiresAt");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_PasswordResetTokens_UserId");

                    b.HasIndex("TokenHash", "ExpiresAt", "UsedAt")
                        .HasDatabaseName("IX_PasswordResetTokens_TokenHash_ExpiresAt_UsedAt");

                    b.ToTable("ResetPasswordTokens");
                });

            modelBuilder.Entity("FootballAPI.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "FC Brasov"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Steaua Bucuresti"
                        });
                });

            modelBuilder.Entity("FootballAPI.Models.TeamPlayers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MatchTeamId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("MatchTeamId", "PlayerId")
                        .IsUnique();

                    b.ToTable("TeamPlayers");
                });

            modelBuilder.Entity("FootballAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ion.popescu@gmail.com",
                            Password = "default123",
                            Role = 2,
                            Username = "IonPopescu"
                        },
                        new
                        {
                            Id = 2,
                            Email = "marius.ionescu@gmail.com",
                            Password = "default123",
                            Role = 2,
                            Username = "MariusIonescu"
                        },
                        new
                        {
                            Id = 3,
                            Email = "admin@gmail.com",
                            Password = "default123",
                            Role = 0,
                            Username = "Admin"
                        },
                        new
                        {
                            Id = 4,
                            Email = "organiser@gmail.com",
                            Password = "default123",
                            Role = 1,
                            Username = "Organiser"
                        },
                        new
                        {
                            Id = 5,
                            Email = "alex.georgescu@gmail.com",
                            Password = "default123",
                            Role = 2,
                            Username = "AlexGeorgescu"
                        },
                        new
                        {
                            Id = 6,
                            Email = "razvan.moldovan@gmail.com",
                            Password = "default123",
                            Role = 2,
                            Username = "RazvanMoldovan"
                        },
                        new
                        {
                            Id = 7,
                            Email = "cristian.stancu@gmail.com",
                            Password = "default123",
                            Role = 2,
                            Username = "CristianStancu"
                        },
                        new
                        {
                            Id = 8,
                            Email = "andrei.vasilescu@gmail.com",
                            Password = "default123",
                            Role = 2,
                            Username = "AndreiVasilescu"
                        },
                        new
                        {
                            Id = 9,
                            Email = "florin.dumitru@gmail.com",
                            Password = "default123",
                            Role = 2,
                            Username = "FlorinDumitru"
                        },
                        new
                        {
                            Id = 10,
                            Email = "gabriel.ciobanu@gmail.com",
                            Password = "default123",
                            Role = 2,
                            Username = "GabrielCiobanu"
                        },
                        new
                        {
                            Id = 11,
                            Email = "lucian.matei@gmail.com",
                            Password = "default123",
                            Role = 2,
                            Username = "LucianMatei"
                        },
                        new
                        {
                            Id = 12,
                            Email = "daniel.radu@gmail.com",
                            Password = "default123",
                            Role = 2,
                            Username = "DanielRadu"
                        },
                        new
                        {
                            Id = 13,
                            Email = "mihai.popa@gmail.com",
                            Password = "default123",
                            Role = 2,
                            Username = "MihaiPopa"
                        },
                        new
                        {
                            Id = 14,
                            Email = "stefan.nicolae@gmail.com",
                            Password = "default123",
                            Role = 2,
                            Username = "StefanNicolae"
                        });
                });

            modelBuilder.Entity("FootballAPI.Models.FriendRequest", b =>
                {
                    b.HasOne("FootballAPI.Models.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FootballAPI.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("FootballAPI.Models.Match", b =>
                {
                    b.HasOne("FootballAPI.Models.Team", null)
                        .WithMany("AwayMatches")
                        .HasForeignKey("TeamId");

                    b.HasOne("FootballAPI.Models.Team", null)
                        .WithMany("HomeMatches")
                        .HasForeignKey("TeamId1");
                });

            modelBuilder.Entity("FootballAPI.Models.MatchTeams", b =>
                {
                    b.HasOne("FootballAPI.Models.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballAPI.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("FootballAPI.Models.Player", b =>
                {
                    b.HasOne("FootballAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FootballAPI.Models.PlayerMatchHistory", b =>
                {
                    b.HasOne("FootballAPI.Models.Match", "Match")
                        .WithMany("PlayerHistory")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballAPI.Models.MatchTeams", null)
                        .WithMany("PlayerHistory")
                        .HasForeignKey("MatchTeamsId");

                    b.HasOne("FootballAPI.Models.Player", "Player")
                        .WithMany("MatchHistory")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballAPI.Models.Team", "Team")
                        .WithMany("PlayerHistory")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("FootballAPI.Models.PlayerOrganiser", b =>
                {
                    b.HasOne("FootballAPI.Models.User", "Organiser")
                        .WithMany()
                        .HasForeignKey("OrganiserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballAPI.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organiser");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("FootballAPI.Models.ResetPasswordToken", b =>
                {
                    b.HasOne("FootballAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FootballAPI.Models.TeamPlayers", b =>
                {
                    b.HasOne("FootballAPI.Models.MatchTeams", "MatchTeam")
                        .WithMany()
                        .HasForeignKey("MatchTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballAPI.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MatchTeam");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("FootballAPI.Models.Match", b =>
                {
                    b.Navigation("PlayerHistory");
                });

            modelBuilder.Entity("FootballAPI.Models.MatchTeams", b =>
                {
                    b.Navigation("PlayerHistory");
                });

            modelBuilder.Entity("FootballAPI.Models.Player", b =>
                {
                    b.Navigation("MatchHistory");
                });

            modelBuilder.Entity("FootballAPI.Models.Team", b =>
                {
                    b.Navigation("AwayMatches");

                    b.Navigation("HomeMatches");

                    b.Navigation("PlayerHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
