name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test-api:
    runs-on: ubuntu-latest
    name: Build and Test .NET API
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Restore dependencies
      run: dotnet restore FootballAPI/FootballAPI.csproj
      
    - name: Build API
      run: dotnet build FootballAPI/FootballAPI.csproj --no-restore --configuration Release
      
    # - name: Run API tests
    #   run: dotnet test FootballAPI.Tests/FootballAPI.Tests.csproj --no-build --configuration Release --verbosity normal
      
    - name: Publish API
      run: dotnet publish FootballAPI/FootballAPI.csproj --configuration Release --output ./api-publish
      
    - name: Upload API artifacts
      uses: actions/upload-artifact@v4
      with:
        name: api-artifacts
        path: ./api-publish/

  build-and-test-client:
    runs-on: ubuntu-latest
    name: Build and Test Angular Client
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: FootballClient/package-lock.json
        
    - name: Install dependencies
      run: npm ci
      working-directory: ./FootballClient
      
    - name: Build client
      run: npm run build
      working-directory: ./FootballClient
      
    # TODO: Add tests when test files are created
    # - name: Test client
    #   run: npm run test -- --watch=false --browsers=ChromeHeadless
    #   working-directory: ./FootballClient
      
    - name: Upload client artifacts
      uses: actions/upload-artifact@v4
      with:
        name: client-artifacts
        path: ./FootballClient/dist/
  
  update-versions:
    runs-on: ubuntu-latest
    name: Update Version Numbers
    needs: [build-and-test-api, build-and-test-client]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
    - name: Read current version
      id: current_version
      run: |
        CURRENT_VERSION=$(cat VERSION)
        echo "current=$CURRENT_VERSION" >> $GITHUB_OUTPUT
        echo "Current version: $CURRENT_VERSION"
        
    - name: Calculate new version
      id: new_version
      run: |
        CURRENT_VERSION="${{ steps.current_version.outputs.current }}"
        IFS='.' read -r major minor patch <<< "$CURRENT_VERSION"
        NEW_PATCH=$((patch + 1))
        NEW_VERSION="$major.$minor.$NEW_PATCH"
        echo "new=$NEW_VERSION" >> $GITHUB_OUTPUT
        echo "New version: $NEW_VERSION"
        
    - name: Update VERSION file
      run: |
        echo "${{ steps.new_version.outputs.new }}" > VERSION
        
    - name: Commit version update
      run: |
        git add VERSION FootballClient/package.json FootballClient/package-lock.json FootballAPI/FootballAPI.csproj
        git commit -m "chore: bump version to ${{ steps.new_version.outputs.new }} [skip ci]"
        git push
    
        
  deploy-production:
    runs-on: ubuntu-latest
    name: Deploy to Production
    needs: [build-and-test-api, build-and-test-client]
    if: github.ref == 'refs/heads/main'
    environment: production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download API artifacts
      uses: actions/download-artifact@v4
      with:
        name: api-artifacts
        path: ./api-artifacts/
        
    - name: Download Client artifacts
      uses: actions/download-artifact@v4
      with:
        name: client-artifacts
        path: ./client-artifacts/
        
    - name: Deploy to production
      run: |
        echo "Deploying to production environment..."
        echo "This is where you would deploy to your production server"
        # Add your production deployment commands here