name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test-api:
    runs-on: ubuntu-latest
    name: Build and Test .NET API
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Restore dependencies
      run: dotnet restore FootballAPI/FootballAPI.csproj
      
    - name: Build API
      run: dotnet build FootballAPI/FootballAPI.csproj --no-restore --configuration Release
      
    # - name: Run API tests
    #   run: dotnet test FootballAPI.Tests/FootballAPI.Tests.csproj --no-build --configuration Release --verbosity normal
      
    - name: Publish API
      run: dotnet publish FootballAPI/FootballAPI.csproj --configuration Release --output ./api-publish
      
    - name: Upload API artifacts
      uses: actions/upload-artifact@v4
      with:
        name: api-artifacts
        path: ./api-publish/

  build-and-test-client:
    runs-on: ubuntu-latest
    name: Build and Test Angular Client
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: FootballClient/package-lock.json
        
    - name: Install dependencies
      run: npm ci
      working-directory: ./FootballClient
      
    - name: Build client
      run: npm run build
      working-directory: ./FootballClient
      
    # TODO: Add tests when test files are created
    # - name: Test client
    #   run: npm run test -- --watch=false --browsers=ChromeHeadless
    #   working-directory: ./FootballClient
      
    - name: Upload client artifacts
      uses: actions/upload-artifact@v4
      with:
        name: client-artifacts
        path: ./FootballClient/dist/


  deploy-staging:
    runs-on: ubuntu-latest
    name: Deploy to Staging
    needs: [build-and-test-api, build-and-test-client]
    if: github.ref == 'refs/heads/develop'
    environment: staging
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download API artifacts
      uses: actions/download-artifact@v4
      with:
        name: api-artifacts
        path: ./api-artifacts/
        
    - name: Download Client artifacts
      uses: actions/download-artifact@v4
      with:
        name: client-artifacts
        path: ./client-artifacts/
        
    - name: Deploy to staging
      run: |
        echo "Deploying to staging environment..."
        echo "This is where you would deploy to your staging server"
        # Add your staging deployment commands here
        
  deploy-production:
    runs-on: ubuntu-latest
    name: Deploy to Production
    needs: [build-and-test-api, build-and-test-client]
    if: github.ref == 'refs/heads/main'
    environment: production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download API artifacts
      uses: actions/download-artifact@v4
      with:
        name: api-artifacts
        path: ./api-artifacts/
        
    - name: Download Client artifacts
      uses: actions/download-artifact@v4
      with:
        name: client-artifacts
        path: ./client-artifacts/
        
    - name: Deploy to production
      run: |
        echo "Deploying to production environment..."
        echo "This is where you would deploy to your production server"
        # Add your production deployment commands here